import type { TranslationInput } from '@/i18n'
import type { WallpaperCanvasPreset, WallpaperWidgetDefinition, WallpaperWidgetInstance, WallpaperWidgetType } from './wallpaper-types'

export const WALLPAPER_WIDGET_DEFINITIONS: WallpaperWidgetDefinition[] = [
  {
    type: 'clock',
    title: { ko: '시계', en: 'Clock' },
    description: { ko: '현재 시간을 크게 표시해 주는 위젯이야.', en: 'Shows the current time in large type.' },
    searchKeywords: ['time', 'timer', 'watch'],
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 6 },
    defaultSettings: {
      // Empty = show the localized widget name; the user can still type their own title.
      title: '',
      showTitle: false,
      showBackground: false,
      showBorder: false,
      timeFormat: '24h',
      showSeconds: false,
      showDate: true,
      visualStyle: 'clean',
    },
  },
  {
    type: 'queue-status',
    title: { ko: '워크플로 상태', en: 'Workflow status' },
    description: { ko: '그래프 실행의 대기, 실행, 실패 상태를 보여줘.', en: 'Shows queued, running and failed graph runs.' },
    searchKeywords: ['queue', 'status', 'workflow', 'run', 'progress'],
    defaultSize: { w: 8, h: 5 },
    minSize: { w: 6, h: 4 },
    maxSize: { w: 12, h: 8 },
    defaultSettings: {
      title: '',
      showTitle: false,
      showBackground: false,
      showBorder: false,
      refreshIntervalSec: 5,
      visualMode: 'tiles',
    },
  },
  {
    type: 'recent-results',
    title: { ko: '최근 결과', en: 'Recent results' },
    description: { ko: '최근 생성 이미지를 빠르게 보여줘.', en: 'Shows your latest generated images.' },
    searchKeywords: ['recent', 'results', 'latest', 'generated', 'history'],
    defaultSize: { w: 10, h: 7 },
    minSize: { w: 6, h: 5 },
    maxSize: { w: 16, h: 10 },
    defaultSettings: {
      title: '',
      showTitle: false,
      showBackground: false,
      showBorder: false,
      refreshIntervalSec: 10,
      visibleCount: 4,
      displayMode: 'stack',
      shiftIntervalSec: 8,
      imageTransitionStyle: 'zoom',
      imageTransitionSpeed: 'normal',
      imageTransitionDurationMs: 340,
      imageTransitionEasing: 'easeOutCubic',
      imageHoverMotion: 1,
      hoverEasing: 'easeOutCubic',
      imagePreviewOpenScalePercent: 88,
      imagePreviewOpenDurationMs: 260,
      imagePreviewOpenEasing: 'easeOutCubic',
      imagePreviewCloseScalePercent: 88,
      imagePreviewCloseDurationMs: 260,
      imagePreviewCloseEasing: 'easeInOutCubic',
    },
  },
  {
    type: 'activity-pulse',
    title: { ko: '실행 펄스', en: 'Activity pulse' },
    description: { ko: '그래프 실행과 최근 결과 흐름을 잔잔하게 시각화해.', en: 'A calm visualization of graph runs and recent results.' },
    searchKeywords: ['activity', 'pulse', 'workflow', 'status', 'visualizer'],
    defaultSize: { w: 10, h: 5 },
    minSize: { w: 7, h: 4 },
    maxSize: { w: 16, h: 8 },
    defaultSettings: {
      title: '',
      showTitle: false,
      showBackground: false,
      showBorder: false,
      refreshIntervalSec: 5,
      motionStrength: 1,
      emphasis: 'mixed',
    },
  },
  {
    type: 'group-image-view',
    title: { ko: '그룹 이미지', en: 'Group images' },
    description: { ko: '선택한 그룹 이미지를 그리드로 보여줘.', en: 'Shows images from a chosen group in a grid.' },
    searchKeywords: ['group', 'gallery', 'grid', 'album'],
    defaultSize: { w: 10, h: 7 },
    minSize: { w: 8, h: 5 },
    maxSize: { w: 16, h: 12 },
    defaultSettings: {
      title: '',
      showTitle: false,
      showBackground: false,
      showBorder: false,
      visibleCount: 6,
      layoutMode: 'grid',
      slideshowIntervalSec: 12,
      motionMode: 'ambient',
      motionStrength: 1,
      motionEasing: 'easeOutCubic',
      imageTransitionStyle: 'fade',
      imageTransitionSpeed: 'normal',
      imageTransitionDurationMs: 340,
      imageTransitionEasing: 'easeOutCubic',
      imageHoverMotion: 1,
      hoverEasing: 'easeOutCubic',
      imageClickAction: 'preview',
      pauseOnHover: true,
      imagePreviewOpenScalePercent: 88,
      imagePreviewOpenDurationMs: 260,
      imagePreviewOpenEasing: 'easeOutCubic',
      imagePreviewCloseScalePercent: 88,
      imagePreviewCloseDurationMs: 260,
      imagePreviewCloseEasing: 'easeInOutCubic',
      groupId: null,
      includeChildren: true,
    },
  },
  {
    type: 'image-showcase',
    title: { ko: '이미지 쇼케이스', en: 'Image showcase' },
    description: { ko: '대표 이미지나 슬라이드쇼 영역으로 써.', en: 'A featured image or slideshow area.' },
    searchKeywords: ['showcase', 'slideshow', 'carousel', 'hero'],
    defaultSize: { w: 12, h: 8 },
    minSize: { w: 8, h: 5 },
    maxSize: { w: 18, h: 12 },
    defaultSettings: {
      title: '',
      showTitle: false,
      showBackground: false,
      showBorder: false,
      fitMode: 'cover',
      slideshowIntervalSec: 20,
      playbackMode: 'carousel',
      imageTransitionStyle: 'fade',
      imageTransitionSpeed: 'normal',
      imageTransitionDurationMs: 340,
      imageTransitionEasing: 'easeOutCubic',
      imageHoverMotion: 1,
      hoverEasing: 'easeOutCubic',
      imageClickAction: 'preview',
      pauseOnHover: true,
      imagePreviewOpenScalePercent: 88,
      imagePreviewOpenDurationMs: 260,
      imagePreviewOpenEasing: 'easeOutCubic',
      imagePreviewCloseScalePercent: 88,
      imagePreviewCloseDurationMs: 260,
      imagePreviewCloseEasing: 'easeInOutCubic',
      groupId: null,
      includeChildren: true,
    },
  },
  {
    type: 'floating-collage',
    title: { ko: '플로팅 콜라주', en: 'Floating collage' },
    description: { ko: '선택한 그룹 이미지로 떠다니는 콜라주를 만들어.', en: 'A drifting collage built from a chosen group.' },
    searchKeywords: ['floating', 'collage', 'motion', 'ambient'],
    defaultSize: { w: 12, h: 8 },
    minSize: { w: 8, h: 6 },
    maxSize: { w: 18, h: 12 },
    defaultSettings: {
      title: '',
      showTitle: false,
      showBackground: false,
      showBorder: false,
      visibleCount: 5,
      motionStrength: 1,
      motionEasing: 'linear',
      motionSpeed: 1,
      imageScalePercent: 100,
      fitMode: 'cover',
      aspectMode: 'image',
      imageSwapMode: 'bounce',
      imageTransitionStyle: 'fade',
      imageTransitionDurationMs: 340,
      imageTransitionEasing: 'easeOutCubic',
      swapIntervalSec: 12,
      swapBounceCount: 3,
      imageHoverMotion: 1,
      hoverEasing: 'easeOutCubic',
      imageClickAction: 'preview',
      imagePreviewOpenScalePercent: 88,
      imagePreviewOpenDurationMs: 260,
      imagePreviewOpenEasing: 'easeOutCubic',
      imagePreviewCloseScalePercent: 88,
      imagePreviewCloseDurationMs: 260,
      imagePreviewCloseEasing: 'easeInOutCubic',
      groupId: null,
      includeChildren: true,
    },
  },
  {
    type: 'text-note',
    title: { ko: '텍스트 노트', en: 'Text note' },
    description: { ko: '짧은 메모나 라벨을 배치해 둘 수 있어.', en: 'Place a short note or label.' },
    searchKeywords: ['text', 'note', 'memo', 'label'],
    defaultSize: { w: 7, h: 4 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 8 },
    defaultSettings: {
      title: '',
      showTitle: false,
      showBackground: false,
      showBorder: false,
      text: '월페이퍼 메모',
    },
  },
]

/** Return the registered wallpaper widget types. */
export function listWallpaperWidgetDefinitions() {
  return WALLPAPER_WIDGET_DEFINITIONS.filter((definition) => definition.type !== 'activity-pulse')
}

/** Find one wallpaper widget definition by type. */
export function getWallpaperWidgetDefinition<T extends WallpaperWidgetType>(widgetType: T): Extract<WallpaperWidgetDefinition, { type: T }> {
  return (WALLPAPER_WIDGET_DEFINITIONS.find((widget) => widget.type === widgetType) ?? WALLPAPER_WIDGET_DEFINITIONS[0]) as Extract<WallpaperWidgetDefinition, { type: T }>
}

/** Return the title to show for a placed widget: the user's own title, else the localized widget name. */
export function getWallpaperWidgetDisplayTitle(widget: WallpaperWidgetInstance, t: (input: TranslationInput) => string): string {
  const customTitle = typeof widget.settings.title === 'string' ? widget.settings.title.trim() : ''
  return customTitle || t(getWallpaperWidgetDefinition(widget.type).title)
}

/** Create one placed widget instance using the widget defaults and a simple grid slot. */
export function createWallpaperWidgetInstance<T extends WallpaperWidgetType>(widgetType: T, canvasPreset: WallpaperCanvasPreset, sequence: number): Extract<WallpaperWidgetInstance, { type: T }> {
  const definition = getWallpaperWidgetDefinition(widgetType)
  const slotWidth = Math.max(1, definition.defaultSize.w)
  const itemsPerRow = Math.max(1, Math.floor(canvasPreset.gridColumns / slotWidth))
  const x = (sequence % itemsPerRow) * slotWidth
  const y = Math.floor(sequence / itemsPerRow) * definition.defaultSize.h

  return {
    id: `${widgetType}-${Date.now()}-${sequence}`,
    type: definition.type,
    x,
    y,
    w: definition.defaultSize.w,
    h: definition.defaultSize.h,
    zIndex: sequence + 1,
    locked: false,
    hidden: false,
    settings: { ...definition.defaultSettings },
  } as Extract<WallpaperWidgetInstance, { type: T }>
}
