const CODEX_MESSAGE_MODEL_OPTIONS = [
  'gpt-5.4',
  'gpt-5.5',
  'gpt-5.4-mini',
  'gpt-5.3-codex',
  'gpt-5.3-codex-spark',
] as const;

const NAI_IMAGE_MODEL_OPTIONS = [
  'nai-diffusion-4-5-curated',
  'nai-diffusion-4-5-full',
  'nai-diffusion-4-curated-preview',
  'nai-diffusion-3',
] as const;

const NAI_IMAGE_ACTION_OPTIONS = ['generate', 'img2img', 'infill'] as const;
const NAI_IMAGE_SAMPLER_OPTIONS = ['k_euler', 'k_euler_ancestral', 'k_dpmpp_2s_ancestral', 'k_dpmpp_2m'] as const;
const NAI_IMAGE_SCHEDULER_OPTIONS = ['karras', 'native', 'exponential', 'polyexponential'] as const;
const IMAGE_GENERATION_ASPECT_RATIO_OPTIONS = ['random', '1:1', '4:3', '3:4', '16:9', '9:16'] as const;
const IMAGE_GENERATION_RESOLUTION_OPTIONS = ['1024', '1536', '2048'] as const;

import type { BuiltinSystemModuleDefinition } from './userSettingsBuiltinModuleDefinitions';

export const BUILTIN_SYSTEM_MODULE_DEFINITIONS: BuiltinSystemModuleDefinition[] = [
  {
    name: '상수 텍스트',
    description: '노드 안에 넣어둔 텍스트를 그대로 꺼내서 다음 단계로 넘겨줘.',
    category: 'input',
    exposedInputs: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
      },
    ],
    outputPorts: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.constant_text' },
    uiSchema: [
      {
        key: 'text',
        label: '텍스트',
        data_type: 'text',
        placeholder: '텍스트 입력',
      },
    ],
    color: '#66bb6a',
    legacyNames: ['텍스트'],
  },
  {
    name: '상수 프롬프트',
    description: '노드 안에 넣어둔 텍스트를 그대로 꺼내서 다음 단계로 넘겨줘.',
    category: 'input',
    exposedInputs: [
      {
        key: 'prompt',
        label: '텍스트',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
      },
    ],
    outputPorts: [
      {
        key: 'prompt',
        label: '텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.constant_prompt' },
    uiSchema: [
      {
        key: 'prompt',
        label: '텍스트',
        data_type: 'text',
        placeholder: '텍스트 입력',
      },
    ],
    color: '#66bb6a',
    legacyNames: ['텍스트', '상수 프롬프트'],
  },
  {
    name: 'JSON',
    description: '노드 안에 넣어둔 JSON 값을 그대로 꺼내서 다음 단계로 넘겨줘.',
    category: 'input',
    exposedInputs: [
      {
        key: 'json',
        label: 'JSON',
        direction: 'input',
        data_type: 'json',
        required: true,
        multiple: false,
      },
    ],
    outputPorts: [
      {
        key: 'json',
        label: 'JSON',
        direction: 'output',
        data_type: 'json',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.constant_json' },
    uiSchema: [
      {
        key: 'json',
        label: 'JSON',
        data_type: 'json',
        placeholder: '{\n  "key": "value"\n}',
      },
    ],
    color: '#78909c',
  },
  {
    name: '이미지',
    description: '노드 안에 넣어둔 이미지를 그대로 꺼내서 다음 단계로 넘겨줘.',
    category: 'input',
    exposedInputs: [
      {
        key: 'image',
        label: '이미지',
        direction: 'input',
        data_type: 'image',
        required: true,
        multiple: false,
      },
    ],
    outputPorts: [
      {
        key: 'image',
        label: '이미지',
        direction: 'output',
        data_type: 'image',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.constant_image' },
    uiSchema: [],
    color: '#29b6f6',
  },
  {
    name: '숫자',
    description: '노드 안에 넣어둔 숫자 값을 그대로 꺼내서 다음 단계로 넘겨줘.',
    category: 'input',
    exposedInputs: [
      {
        key: 'number',
        label: '숫자',
        direction: 'input',
        data_type: 'number',
        required: true,
        multiple: false,
      },
    ],
    outputPorts: [
      {
        key: 'number',
        label: '숫자',
        direction: 'output',
        data_type: 'number',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.constant_number' },
    uiSchema: [
      {
        key: 'number',
        label: '숫자',
        data_type: 'number',
      },
    ],
    color: '#ffd54f',
  },
  {
    name: '불리언',
    description: '노드 안에 넣어둔 참/거짓 값을 그대로 꺼내서 다음 단계로 넘겨줘.',
    category: 'input',
    exposedInputs: [
      {
        key: 'boolean',
        label: '불리언',
        direction: 'input',
        data_type: 'boolean',
        required: true,
        multiple: false,
      },
    ],
    outputPorts: [
      {
        key: 'boolean',
        label: '불리언',
        direction: 'output',
        data_type: 'boolean',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.constant_boolean' },
    uiSchema: [
      {
        key: 'boolean',
        label: '불리언',
        data_type: 'select',
        options: ['true', 'false'],
      },
    ],
    color: '#ef9a9a',
  },
  {
    name: '텍스트 합치기',
    description: 'A, B, C 텍스트를 순서대로 붙여서 하나의 텍스트로 만들어. A-B와 B-C 사이 구분자는 노드 안에서 바로 바꿀 수 있어.',
    category: 'utility',
    exposedInputs: [
      {
        key: 'text_a',
        label: 'A',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '첫 번째 텍스트 조각이야.',
      },
      {
        key: 'text_b',
        label: 'B',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '두 번째 텍스트 조각이야.',
      },
      {
        key: 'text_c',
        label: 'C',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '세 번째 텍스트 조각이야.',
      },
    ],
    outputPorts: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.merge_text' },
    uiSchema: [
      {
        key: 'separator_ab',
        label: 'A 뒤 문자열',
        data_type: 'text',
        default_value: ',',
        placeholder: '예: , 또는 줄바꿈',
        description: 'A 항목 뒤에 붙일 문자열이야.',
      },
      {
        key: 'separator_bc',
        label: 'B 뒤 문자열',
        data_type: 'text',
        default_value: ',',
        placeholder: '예: , 또는 줄바꿈',
        description: 'B 항목 뒤에 붙일 문자열이야.',
      },
    ],
    color: '#4db6ac',
  },
  {
    name: '랜덤 텍스트 선택',
    description: '연결된 텍스트 후보 중 하나를 무작위로 골라 하나의 텍스트로 내보내.',
    category: 'utility',
    exposedInputs: [
      {
        key: 'options',
        label: '텍스트 후보',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        default_value: [
          { key: 'text_1', value: '' },
          { key: 'text_2', value: '' },
        ],
        description: '노드 카드에서 후보 행을 추가하고 각 행에 텍스트 노드를 연결해.',
      },
    ],
    outputPorts: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.random_text_choice' },
    uiSchema: [
      {
        key: 'options',
        label: '텍스트 후보',
        data_type: 'json',
        default_value: [
          { key: 'text_1', value: '' },
          { key: 'text_2', value: '' },
        ],
        ui_hint: 'random_text_entries',
      },
    ],
    color: '#4db6ac',
  },
  {
    name: '와일드카드 적용',
    description: '입력 텍스트의 와일드카드를 General, NAI, ComfyUI 규칙으로 각각 적용해서 포트별로 내보내.',
    category: 'utility',
    exposedInputs: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'input',
        data_type: 'prompt',
        required: true,
        multiple: false,
        description: '++이름++ 와일드카드가 들어간 원본 텍스트야.',
      },
    ],
    outputPorts: [
      {
        key: 'general',
        label: 'General',
        direction: 'output',
        data_type: 'prompt',
        required: true,
        multiple: false,
        description: 'General 항목만 사용해서 적용한 결과야.',
      },
      {
        key: 'nai',
        label: 'NAI',
        direction: 'output',
        data_type: 'prompt',
        required: true,
        multiple: false,
        description: 'NAI 항목을 우선 쓰고 없으면 General 항목으로 적용한 결과야.',
      },
      {
        key: 'comfyui',
        label: 'ComfyUI',
        direction: 'output',
        data_type: 'prompt',
        required: true,
        multiple: false,
        description: 'ComfyUI 항목을 우선 쓰고 없으면 General 항목으로 적용한 결과야.',
      },
    ],
    internalFixedValues: { operation_key: 'system.apply_wildcards' },
    uiSchema: [
      {
        key: 'text',
        label: '텍스트',
        data_type: 'prompt',
        placeholder: '예: ++character++, ++pose++',
        description: '그래프 입력으로 연결하지 않을 때 노드 안에서 바로 쓸 원본 텍스트야.',
      },
    ],
    color: '#ab47bc',
  },
  {
    name: 'LLM 호출',
    description: 'LM Studio, Ollama, 또는 OpenAI 호환 LLM 연결을 호출해서 텍스트나 JSON 응답을 받아와.',
    category: 'llm',
    exposedInputs: [
      {
        key: 'prompt',
        label: '프롬프트',
        direction: 'input',
        data_type: 'prompt',
        required: false,
        multiple: false,
        description: 'LLM에 보낼 본문이야.',
      },
      {
        key: 'system_prompt',
        label: '시스템 프롬프트',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '모델의 기본 행동을 정하고 싶을 때 써.',
      },
      {
        key: 'context',
        label: '컨텍스트',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '프롬프트에 함께 전달할 참고 문맥이야.',
      },
      {
        key: 'image',
        label: '이미지',
        direction: 'input',
        data_type: 'image',
        required: false,
        multiple: false,
        description: '비전 모델에 함께 전달할 선택 이미지야.',
      },
      {
        key: 'provider_name',
        label: '연결 이름',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
        description: 'external_api_providers에 저장된 연결 이름이야.',
      },
      {
        key: 'model',
        label: '모델',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '비워두면 연결의 기본 모델을 우선 사용해.',
      },
      {
        key: 'structured_output_json',
        label: '구조화 출력 JSON',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        description: '응답이 맞춰야 할 JSON 예시/양식이야. 값이 있으면 JSON 모드로 강제해.',
      },
      {
        key: 'temperature',
        label: '온도',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
      },
      {
        key: 'max_tokens',
        label: '최대 토큰',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
      },
    ],
    outputPorts: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
      {
        key: 'json',
        label: 'JSON',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
      {
        key: 'metadata',
        label: '메타데이터',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.call_llm' },
    uiSchema: [
      {
        key: 'provider_name',
        label: '연결 이름',
        data_type: 'text',
        placeholder: '예: lmstudio-local / ollama-local',
      },
      {
        key: 'model',
        label: '모델',
        data_type: 'text',
        placeholder: '예: qwen2.5-coder:7b / local-model',
      },
      {
        key: 'prompt',
        label: '프롬프트',
        data_type: 'prompt',
        placeholder: 'LLM에게 보낼 지시를 입력해',
      },
      {
        key: 'system_prompt',
        label: '시스템 프롬프트',
        data_type: 'text',
        placeholder: '선택: 역할/규칙',
      },
      {
        key: 'context',
        label: '컨텍스트',
        data_type: 'text',
        placeholder: '선택: 참고 문맥',
      },
      {
        key: 'image',
        label: '이미지',
        data_type: 'image',
      },
      {
        key: 'structured_output_json',
        label: '구조화 출력 JSON',
        data_type: 'json',
        placeholder: '{\n  "field": "value"\n}',
      },
      {
        key: 'temperature',
        label: '온도',
        data_type: 'number',
      },
      {
        key: 'max_tokens',
        label: '최대 토큰',
        data_type: 'number',
      },
    ],
    color: '#7e57c2',
  },
  {
    name: 'LLM 프리셋 불러오기',
    description: '저장된 LLM 프리셋 종류와 항목을 선택해서 워크플로우 값으로 꺼내와.',
    category: 'llm',
    exposedInputs: [
      {
        key: 'preset_type',
        label: '프리셋 종류',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
        default_value: 'promptPresets',
        description: 'systemPromptPresets, promptPresets, structuredOutputJsonPresets 중 하나야.',
      },
      {
        key: 'preset_name',
        label: '프리셋 항목',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
        description: '선택한 종류 안에 저장된 프리셋 이름이야.',
      },
    ],
    outputPorts: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
      {
        key: 'json',
        label: 'JSON',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.load_llm_preset' },
    uiSchema: [
      {
        key: 'preset_type',
        label: '프리셋 종류',
        data_type: 'select',
        default_value: 'promptPresets',
        options: ['systemPromptPresets', 'promptPresets', 'structuredOutputJsonPresets'],
      },
      {
        key: 'preset_name',
        label: '프리셋 항목',
        data_type: 'select',
        placeholder: '프리셋 선택',
      },
    ],
    color: '#9575cd',
  },
  {
    name: '그룹 랜덤 프롬프트',
    description: '저장된 프롬프트 그룹에서 항목 하나를 뽑아 재사용 가능한 워크플로우 텍스트로 꺼내와.',
    category: 'prompt',
    exposedInputs: [
      {
        key: 'group_name',
        label: '그룹 이름',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: 'group_id가 없을 때 샘플링할 프롬프트 그룹 이름이야.',
      },
      {
        key: 'group_id',
        label: '그룹 ID',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        description: '프롬프트 그룹 ID야. 값이 있으면 그룹 이름보다 우선해.',
      },
      {
        key: 'type',
        label: '컬렉션 종류',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'positive',
        description: 'positive, negative, auto 중 하나를 사용해.',
      },
      {
        key: 'seed',
        label: '시드',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        description: '선택 결과를 고정하고 싶을 때 쓰는 시드야.',
      },
    ],
    outputPorts: [
      {
        key: 'prompt',
        label: '프롬프트',
        direction: 'output',
        data_type: 'prompt',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.random_prompt_from_group' },
    uiSchema: [
      {
        key: 'group_name',
        label: '그룹 이름',
        data_type: 'text',
        placeholder: '예: 캐릭터 포즈 / 의상 / 자동 태그',
      },
      {
        key: 'group_id',
        label: '그룹 ID',
        data_type: 'number',
      },
      {
        key: 'type',
        label: '컬렉션 종류',
        data_type: 'select',
        default_value: 'positive',
        options: ['positive', 'negative', 'auto'],
      },
      {
        key: 'seed',
        label: '시드',
        data_type: 'number',
      },
    ],
    color: '#26a69a',
  },
  {
    name: '유사 이미지 찾기',
    description: '입력 이미지 하나를 기준으로 현재 라이브러리에서 비슷한 이미지를 찾아줘.',
    category: 'image',
    exposedInputs: [
      {
        key: 'image',
        label: '이미지',
        direction: 'input',
        data_type: 'image',
        required: true,
        multiple: false,
        description: '유사 이미지 검색 기준으로 사용할 입력 이미지야.',
      },
      {
        key: 'limit',
        label: '개수',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 12,
        description: '반환할 유사 이미지 최대 개수야.',
      },
      {
        key: 'threshold',
        label: '임계값',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 15,
        description: '일치로 볼 수 있는 최대 지각 해시 거리야.',
      },
      {
        key: 'include_prompt',
        label: '프롬프트 포함',
        direction: 'input',
        data_type: 'boolean',
        required: false,
        multiple: false,
        default_value: true,
        description: '각 결과에 프롬프트 메타데이터를 함께 포함할지 정해.',
      },
    ],
    outputPorts: [
      {
        key: 'matches',
        label: '검색 결과',
        direction: 'output',
        data_type: 'json',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.find_similar_images' },
    uiSchema: [
      {
        key: 'limit',
        label: '개수',
        data_type: 'number',
        default_value: 12,
      },
      {
        key: 'threshold',
        label: '임계값',
        data_type: 'number',
        default_value: 15,
      },
      {
        key: 'include_prompt',
        label: '프롬프트 포함',
        data_type: 'boolean',
        default_value: true,
      },
    ],
    color: '#42a5f5',
  },
  {
    name: '참조에서 프롬프트 불러오기',
    description: '이미지 참조 정보를 재사용 가능한 프롬프트 텍스트와 메타데이터로 변환해.',
    category: 'prompt',
    exposedInputs: [
      {
        key: 'reference',
        label: '참조',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        description: '유사 이미지 찾기 같은 노드가 만든 구조화된 참조 JSON이야.',
      },
      {
        key: 'composite_hash',
        label: '컴포지트 해시',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '이미지의 직접 컴포지트 해시야. 있으면 참조 JSON보다 우선해.',
      },
      {
        key: 'index',
        label: '인덱스',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 0,
        description: '참조에 items 배열이 있을 때 읽어올 항목 순서야.',
      },
    ],
    outputPorts: [
      {
        key: 'prompt',
        label: '프롬프트',
        direction: 'output',
        data_type: 'prompt',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.load_prompt_from_reference' },
    uiSchema: [
      {
        key: 'composite_hash',
        label: '컴포지트 해시',
        data_type: 'text',
      },
      {
        key: 'index',
        label: '인덱스',
        data_type: 'number',
        default_value: 0,
      },
    ],
    color: '#66bb6a',
  },
  {
    name: '참조에서 이미지 불러오기',
    description: '이미지 참조 정보를 실제 그래프 이미지 아티팩트로 불러와.',
    category: 'image',
    exposedInputs: [
      {
        key: 'reference',
        label: '참조',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        description: '유사 이미지 찾기 같은 노드가 만든 구조화된 참조 JSON이야.',
      },
      {
        key: 'composite_hash',
        label: '컴포지트 해시',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '이미지의 직접 컴포지트 해시야. 있으면 참조 JSON보다 우선해.',
      },
      {
        key: 'index',
        label: '인덱스',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 0,
        description: '참조에 items 배열이 있을 때 읽어올 항목 순서야.',
      },
    ],
    outputPorts: [
      {
        key: 'image',
        label: '이미지',
        direction: 'output',
        data_type: 'image',
        required: true,
        multiple: false,
      },
      {
        key: 'image_ref',
        label: '이미지 참조',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.load_image_from_reference' },
    uiSchema: [
      {
        key: 'composite_hash',
        label: '컴포지트 해시',
        data_type: 'text',
      },
      {
        key: 'index',
        label: '인덱스',
        data_type: 'number',
        default_value: 0,
      },
    ],
    color: '#29b6f6',
  },
  {
    name: '라이브러리 랜덤 이미지',
    description: '현재 라이브러리에서 이미지 하나를 무작위로 골라 재사용 가능한 그래프 이미지로 꺼내와.',
    category: 'image',
    exposedInputs: [],
    outputPorts: [
      {
        key: 'image',
        label: '이미지',
        direction: 'output',
        data_type: 'image',
        required: true,
        multiple: false,
      },
      {
        key: 'image_ref',
        label: '이미지 참조',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
      {
        key: 'metadata',
        label: '메타데이터',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.random_image_from_library' },
    uiSchema: [],
    color: '#7e57c2',
  },
  {
    name: '라이브러리 랜덤 비디오',
    description: '현재 라이브러리에서 비디오 하나를 무작위로 골라 재사용 가능한 그래프 결과물로 꺼내와.',
    category: 'video',
    exposedInputs: [],
    outputPorts: [
      {
        key: 'video',
        label: '비디오',
        direction: 'output',
        data_type: 'any',
        required: true,
        multiple: false,
      },
      {
        key: 'video_ref',
        label: '비디오 참조',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
      {
        key: 'metadata',
        label: '메타데이터',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.random_video_from_library' },
    uiSchema: [],
    color: '#5c6bc0',
  },
  {
    name: 'Codex 메시지',
    description: 'Codex에 단발성 메시지를 보내서 텍스트나 JSON 응답을 받아와.',
    category: 'llm',
    exposedInputs: [
      {
        key: 'prompt',
        label: '프롬프트',
        direction: 'input',
        data_type: 'prompt',
        required: true,
        multiple: false,
        description: 'Codex에 보낼 메인 지시야.',
      },
      {
        key: 'system_prompt',
        label: '시스템 프롬프트',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '행동 규칙을 덧붙이고 싶을 때 써.',
      },
      {
        key: 'context',
        label: '컨텍스트',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '추가 참고 문맥이야.',
      },
      {
        key: 'image',
        label: '이미지',
        direction: 'input',
        data_type: 'image',
        required: false,
        multiple: false,
        description: '비전 모델에 함께 전달할 선택 이미지야.',
      },
      {
        key: 'model',
        label: '모델',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'gpt-5.4',
        description: 'Codex 메시지 모델이야. 기본값은 gpt-5.4야.',
      },
      {
        key: 'structured_output_json',
        label: '구조화 출력 JSON',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        description: '응답이 맞춰야 할 JSON 예시/양식이야. 값이 있으면 JSON 모드로 강제해.',
      },
    ],
    outputPorts: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
      {
        key: 'json',
        label: 'JSON',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
      {
        key: 'metadata',
        label: '메타데이터',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.call_codex_message' },
    uiSchema: [
      {
        key: 'model',
        label: '모델',
        data_type: 'select',
        default_value: 'gpt-5.4',
        options: [...CODEX_MESSAGE_MODEL_OPTIONS],
      },
      {
        key: 'prompt',
        label: '프롬프트',
        data_type: 'prompt',
        placeholder: 'Codex에게 보낼 지시를 입력해',
      },
      {
        key: 'system_prompt',
        label: '시스템 프롬프트',
        data_type: 'text',
        placeholder: '선택: 역할/규칙',
      },
      {
        key: 'context',
        label: '컨텍스트',
        data_type: 'text',
        placeholder: '선택: 참고 문맥',
      },
      {
        key: 'image',
        label: '이미지',
        data_type: 'image',
      },
      {
        key: 'structured_output_json',
        label: '구조화 출력 JSON',
        data_type: 'json',
        placeholder: '{\n  "field": "value"\n}',
      },
    ],
    color: '#5c6bc0',
  },
  {
    name: 'NovelAI 이미지 생성',
    description: 'NovelAI 생성, 이미지 변형, 인페인트에 필요한 설정을 하나의 고정 노드에서 처리해.',
    category: 'generation',
    exposedInputs: [
      {
        key: 'prompt',
        label: '프롬프트',
        direction: 'input',
        data_type: 'prompt',
        required: true,
        multiple: false,
        description: 'NovelAI 이미지 생성에 보낼 메인 프롬프트야.',
      },
      {
        key: 'negative_prompt',
        label: '네거티브 프롬프트',
        direction: 'input',
        data_type: 'prompt',
        required: false,
        multiple: false,
        default_value: '',
        description: '피하고 싶은 요소를 적어.',
      },
      {
        key: 'model',
        label: '모델',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'nai-diffusion-4-5-curated',
      },
      {
        key: 'action',
        label: '작업',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'generate',
        description: 'generate, img2img, infill 중 하나를 선택해.',
      },
      {
        key: 'sampler',
        label: '샘플러',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'k_euler',
      },
      {
        key: 'noise_schedule',
        label: '스케줄러',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'karras',
      },
      {
        key: 'width',
        label: '너비',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 1024,
      },
      {
        key: 'height',
        label: '높이',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 1024,
      },
      {
        key: 'steps',
        label: '스텝',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 28,
      },
      {
        key: 'scale',
        label: 'CFG Scale',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 6,
      },
      {
        key: 'n_samples',
        label: '생성 수',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 1,
        description: 'NovelAI에 요청할 이미지 수야. 그래프 출력은 첫 번째 결과 이미지를 대표값으로 사용해.',
      },
      {
        key: 'seed',
        label: '시드',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        description: '비워두면 실행 시 랜덤 시드를 사용해.',
      },
      {
        key: 'variety_plus',
        label: 'Variety+',
        direction: 'input',
        data_type: 'boolean',
        required: false,
        multiple: false,
        default_value: false,
      },
      {
        key: 'use_coords',
        label: '캐릭터 위치 사용',
        direction: 'input',
        data_type: 'boolean',
        required: false,
        multiple: false,
        default_value: false,
      },
      {
        key: 'characters',
        label: '캐릭터 프롬프트',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        default_value: [],
        description: 'NAI v4 캐릭터 프롬프트 행 배열이야.',
      },
      {
        key: 'vibes',
        label: 'Vibe Transfer',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        default_value: [],
      },
      {
        key: 'character_refs',
        label: '캐릭터 참조',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        default_value: [],
      },
      {
        key: 'image',
        label: '원본 이미지',
        direction: 'input',
        data_type: 'image',
        required: false,
        multiple: false,
        description: 'img2img 또는 infill 작업에 사용할 입력 이미지야.',
      },
      {
        key: 'mask',
        label: '마스크 이미지',
        direction: 'input',
        data_type: 'mask',
        required: false,
        multiple: false,
        description: 'infill 작업의 편집 영역 마스크야.',
      },
      {
        key: 'strength',
        label: '강도',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 0.3,
      },
      {
        key: 'noise',
        label: '노이즈',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 0,
      },
      {
        key: 'add_original_image',
        label: '원본 이미지 유지',
        direction: 'input',
        data_type: 'boolean',
        required: false,
        multiple: false,
        default_value: true,
      },
    ],
    outputPorts: [
      {
        key: 'image',
        label: '이미지',
        direction: 'output',
        data_type: 'image',
        required: true,
        multiple: false,
      },
      {
        key: 'metadata',
        label: '메타데이터',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.generate_image_nai' },
    uiSchema: [
      {
        key: 'prompt',
        label: '프롬프트',
        data_type: 'prompt',
        placeholder: '예: cinematic portrait of a silver-haired android under neon rain',
      },
      {
        key: 'negative_prompt',
        label: '네거티브 프롬프트',
        data_type: 'prompt',
        default_value: '',
        placeholder: '예: blurry, low detail, extra fingers',
      },
      {
        key: 'model',
        label: '모델',
        data_type: 'select',
        default_value: 'nai-diffusion-4-5-curated',
        options: [...NAI_IMAGE_MODEL_OPTIONS],
      },
      {
        key: 'action',
        label: '작업',
        data_type: 'select',
        default_value: 'generate',
        options: [...NAI_IMAGE_ACTION_OPTIONS],
      },
      {
        key: 'sampler',
        label: '샘플러',
        data_type: 'select',
        default_value: 'k_euler',
        options: [...NAI_IMAGE_SAMPLER_OPTIONS],
      },
      {
        key: 'noise_schedule',
        label: '스케줄러',
        data_type: 'select',
        default_value: 'karras',
        options: [...NAI_IMAGE_SCHEDULER_OPTIONS],
      },
      {
        key: 'width',
        label: '너비',
        data_type: 'number',
        default_value: 1024,
        min: 64,
        max: 4096,
      },
      {
        key: 'height',
        label: '높이',
        data_type: 'number',
        default_value: 1024,
        min: 64,
        max: 4096,
      },
      {
        key: 'steps',
        label: '스텝',
        data_type: 'number',
        default_value: 28,
        min: 1,
        max: 50,
      },
      {
        key: 'scale',
        label: 'CFG Scale',
        data_type: 'number',
        default_value: 6,
        min: 0,
        max: 20,
      },
      {
        key: 'n_samples',
        label: '생성 수',
        data_type: 'number',
        default_value: 1,
        min: 1,
        max: 4,
      },
      {
        key: 'seed',
        label: '시드',
        data_type: 'number',
        placeholder: '비워두면 랜덤',
      },
      {
        key: 'variety_plus',
        label: 'Variety+',
        data_type: 'boolean',
        default_value: false,
      },
      {
        key: 'use_coords',
        label: '캐릭터 위치 사용',
        data_type: 'boolean',
        default_value: false,
      },
      {
        key: 'characters',
        label: '캐릭터 프롬프트',
        data_type: 'json',
        default_value: [],
      },
      {
        key: 'vibes',
        label: 'Vibe Transfer',
        data_type: 'json',
        default_value: [],
      },
      {
        key: 'character_refs',
        label: '캐릭터 참조',
        data_type: 'json',
        default_value: [],
      },
      {
        key: 'image',
        label: '원본 이미지',
        data_type: 'image',
      },
      {
        key: 'mask',
        label: '마스크 이미지',
        data_type: 'mask',
      },
      {
        key: 'strength',
        label: '강도',
        data_type: 'number',
        default_value: 0.3,
        min: 0,
        max: 1,
      },
      {
        key: 'noise',
        label: '노이즈',
        data_type: 'number',
        default_value: 0,
        min: 0,
        max: 1,
      },
      {
        key: 'add_original_image',
        label: '원본 이미지 유지',
        data_type: 'boolean',
        default_value: true,
      },
    ],
    color: '#7c4dff',
  },
  {
    name: 'Codex 이미지 생성',
    description: 'Codex를 새 에페메랄 세션으로 실행해서 생성, 편집, 인페인트 결과를 CoNAI 이미지 파이프라인으로 가져와.',
    category: 'generation',
    exposedInputs: [
      {
        key: 'prompt',
        label: '프롬프트',
        direction: 'input',
        data_type: 'prompt',
        required: true,
        multiple: false,
        description: 'Codex 이미지 생성에 보낼 메인 프롬프트야.',
      },
      {
        key: 'negative_prompt',
        label: '네거티브 프롬프트',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: '',
        description: '피하고 싶은 요소를 적어두면 메타데이터에도 함께 남겨.',
      },
      {
        key: 'aspect_ratio',
        label: '비율',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: '1:1',
        description: '원하는 출력 비율이야. random이면 실행할 때마다 비율을 하나 고른다.',
      },
      {
        key: 'resolution',
        label: '해상도',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: '1024',
        description: '긴 변 기준 해상도 프리셋이야.',
      },
      {
        key: 'count',
        label: '생성 수',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 1,
        description: '큐에 요청할 이미지 수야. 그래프 출력은 첫 번째 결과 이미지를 대표값으로 사용해.',
      },
      {
        key: 'image',
        label: '참조 이미지',
        direction: 'input',
        data_type: 'image',
        required: false,
        multiple: false,
        description: '편집이나 인페인트에 사용할 입력 이미지야.',
      },
      {
        key: 'mask',
        label: '마스크 이미지',
        direction: 'input',
        data_type: 'mask',
        required: false,
        multiple: false,
        description: '인페인트 영역을 지정하는 마스크야. 참조 이미지가 필요해.',
      },
    ],
    outputPorts: [
      {
        key: 'image',
        label: '이미지',
        direction: 'output',
        data_type: 'image',
        required: true,
        multiple: false,
      },
      {
        key: 'image_ref',
        label: '이미지 참조',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
      {
        key: 'metadata',
        label: '메타데이터',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.generate_image_codex' },
    uiSchema: [
      {
        key: 'prompt',
        label: '프롬프트',
        data_type: 'text',
        placeholder: '예: cinematic portrait of a silver-haired android under neon rain',
      },
      {
        key: 'negative_prompt',
        label: '네거티브 프롬프트',
        data_type: 'text',
        placeholder: '예: blurry, low detail, extra fingers',
      },
      {
        key: 'aspect_ratio',
        label: '비율',
        data_type: 'select',
        default_value: '1:1',
        options: [...IMAGE_GENERATION_ASPECT_RATIO_OPTIONS],
      },
      {
        key: 'resolution',
        label: '해상도',
        data_type: 'select',
        default_value: '1024',
        options: [...IMAGE_GENERATION_RESOLUTION_OPTIONS],
      },
      {
        key: 'count',
        label: '생성 수',
        data_type: 'number',
        default_value: 1,
        min: 1,
        max: 4,
      },
      {
        key: 'image',
        label: '참조 이미지',
        data_type: 'image',
      },
      {
        key: 'mask',
        label: '마스크 이미지',
        data_type: 'mask',
      },
    ],
    color: '#26a69a',
  },
  {
    name: '이미지에서 태그 추출',
    description: '설정된 이미지 태거를 실행해서 프롬프트에 쓰기 좋은 태그를 추출해.',
    category: 'analysis',
    exposedInputs: [
      {
        key: 'image',
        label: '이미지',
        direction: 'input',
        data_type: 'image',
        required: true,
        multiple: false,
        description: '태그를 추출할 입력 이미지야.',
      },
    ],
    outputPorts: [
      {
        key: 'tags_text',
        label: '태그 텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
      {
        key: 'tags_json',
        label: '태그 JSON',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.extract_tags_from_image' },
    uiSchema: [],
    color: '#ab47bc',
  },
  {
    name: '최종 결과',
    description: '업스트림 결과물 하나를 복제 없이 워크플로우의 최종 결과로 확정해.',
    category: 'output',
    exposedInputs: [
      {
        key: 'value',
        label: '값',
        direction: 'input',
        data_type: 'any',
        required: true,
        multiple: false,
        description: '최종 워크플로우 결과로 기록할 업스트림 결과물 하나를 연결해.',
      },
    ],
    outputPorts: [],
    internalFixedValues: { operation_key: 'system.final_result' },
    uiSchema: [],
    color: '#ffa726',
  },
  {
    name: '중단',
    description: '입력값이 도달하면 워크플로우 실행을 의도적으로 중단해.',
    category: 'output',
    exposedInputs: [
      {
        key: 'condition',
        label: '트리거',
        direction: 'input',
        data_type: 'any',
        required: true,
        multiple: false,
        description: '이 입력에 값이 도달하면 값 내용과 관계없이 워크플로우 실행을 중단해.',
      },
      {
        key: 'reason',
        label: '사유',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        description: '실행 로그에 남길 선택 중단 사유야.',
      },
    ],
    outputPorts: [],
    internalFixedValues: { operation_key: 'system.workflow_stop' },
    uiSchema: [],
    color: '#ef5350',
  },
  {
    name: 'AND',
    description: '두 불리언 입력이 모두 참일 때 참을 출력해.',
    category: 'logic',
    exposedInputs: [
      { key: 'left', label: 'A', direction: 'input', data_type: 'boolean', required: true, multiple: false },
      { key: 'right', label: 'B', direction: 'input', data_type: 'boolean', required: true, multiple: false },
    ],
    outputPorts: [
      { key: 'result', label: '결과', direction: 'output', data_type: 'boolean', required: true, multiple: false },
    ],
    internalFixedValues: { operation_key: 'system.logic_and' },
    uiSchema: [],
    color: '#26a69a',
  },
  {
    name: 'OR',
    description: '두 불리언 입력 중 하나라도 참이면 참을 출력해.',
    category: 'logic',
    exposedInputs: [
      { key: 'left', label: 'A', direction: 'input', data_type: 'boolean', required: true, multiple: false },
      { key: 'right', label: 'B', direction: 'input', data_type: 'boolean', required: true, multiple: false },
    ],
    outputPorts: [
      { key: 'result', label: '결과', direction: 'output', data_type: 'boolean', required: true, multiple: false },
    ],
    internalFixedValues: { operation_key: 'system.logic_or' },
    uiSchema: [],
    color: '#26a69a',
  },
  {
    name: 'NOT',
    description: '불리언 입력을 반전해서 출력해.',
    category: 'logic',
    exposedInputs: [
      { key: 'value', label: '값', direction: 'input', data_type: 'boolean', required: true, multiple: false },
    ],
    outputPorts: [
      { key: 'result', label: '결과', direction: 'output', data_type: 'boolean', required: true, multiple: false },
    ],
    internalFixedValues: { operation_key: 'system.logic_not' },
    uiSchema: [],
    color: '#26a69a',
  },
  {
    name: '비교',
    description: '두 값을 선택한 연산자로 비교해서 불리언 결과를 출력해.',
    category: 'logic',
    exposedInputs: [
      { key: 'left', label: '왼쪽 값', direction: 'input', data_type: 'any', required: true, multiple: false },
      { key: 'right', label: '오른쪽 값', direction: 'input', data_type: 'any', required: true, multiple: false },
    ],
    outputPorts: [
      { key: 'result', label: '결과', direction: 'output', data_type: 'boolean', required: true, multiple: false },
    ],
    internalFixedValues: { operation_key: 'system.logic_compare' },
    uiSchema: [
      {
        key: 'operator',
        label: '연산자',
        data_type: 'select',
        default_value: 'equals',
        options: ['equals', 'not_equals', 'greater_than', 'greater_than_or_equal', 'less_than', 'less_than_or_equal'],
      },
    ],
    color: '#42a5f5',
  },
  {
    name: '텍스트 매치',
    description: '텍스트가 검색어 또는 정규식 조건과 맞는지 검사해.',
    category: 'logic',
    exposedInputs: [
      { key: 'text', label: '텍스트', direction: 'input', data_type: 'text', required: true, multiple: false },
      { key: 'query', label: '검색어', direction: 'input', data_type: 'text', required: true, multiple: false },
    ],
    outputPorts: [
      { key: 'result', label: '결과', direction: 'output', data_type: 'boolean', required: true, multiple: false },
    ],
    internalFixedValues: { operation_key: 'system.logic_text_match' },
    uiSchema: [
      {
        key: 'mode',
        label: '매치 방식',
        data_type: 'select',
        default_value: 'contains',
        options: ['contains', 'not_contains', 'starts_with', 'ends_with', 'regex'],
      },
    ],
    color: '#42a5f5',
  },
  {
    name: '값 존재 여부',
    description: '입력 값이 비어 있는지 또는 존재하는지 검사해.',
    category: 'logic',
    exposedInputs: [
      { key: 'value', label: '값', direction: 'input', data_type: 'any', required: false, multiple: false },
    ],
    outputPorts: [
      { key: 'result', label: '결과', direction: 'output', data_type: 'boolean', required: true, multiple: false },
    ],
    internalFixedValues: { operation_key: 'system.logic_value_presence' },
    uiSchema: [
      {
        key: 'mode',
        label: '검사 방식',
        data_type: 'select',
        default_value: 'exists',
        options: ['exists', 'empty', 'not_empty'],
      },
    ],
    color: '#7e57c2',
  },
  {
    name: '조건 선택',
    description: '조건에 따라 참 값 또는 거짓 값 중 하나를 다음 노드로 넘겨줘.',
    category: 'logic',
    exposedInputs: [
      { key: 'condition', label: '조건', direction: 'input', data_type: 'boolean', required: true, multiple: false },
      { key: 'true_value', label: '참 값', direction: 'input', data_type: 'any', required: true, multiple: false },
      { key: 'false_value', label: '거짓 값', direction: 'input', data_type: 'any', required: true, multiple: false },
    ],
    outputPorts: [
      { key: 'value', label: '값', direction: 'output', data_type: 'any', required: true, multiple: false },
    ],
    internalFixedValues: { operation_key: 'system.logic_condition_select' },
    uiSchema: [],
    color: '#7e57c2',
  },
  {
    name: 'IF 분기',
    description: '입력값을 설정한 조건으로 검사하고 참 또는 거짓 경로로 원본 값을 그대로 넘겨줘.',
    category: 'logic',
    exposedInputs: [
      {
        key: 'value',
        label: '입력값',
        direction: 'input',
        data_type: 'any',
        required: false,
        multiple: false,
        description: '검사하고 다음 경로로 그대로 전달할 원본 값이야.',
      },
      {
        key: 'compare_value',
        label: '비교 값',
        direction: 'input',
        data_type: 'any',
        required: false,
        multiple: false,
        description: '비교, 텍스트 매치, 타입 검사 등에 사용할 기준 값이야.',
      },
    ],
    outputPorts: [
      { key: 'true_value', label: '참', direction: 'output', data_type: 'any', required: false, multiple: false },
      { key: 'false_value', label: '거짓', direction: 'output', data_type: 'any', required: false, multiple: false },
      { key: 'result', label: '결과', direction: 'output', data_type: 'boolean', required: true, multiple: false },
    ],
    internalFixedValues: { operation_key: 'system.logic_if_branch' },
    uiSchema: [
      {
        key: 'mode',
        label: '조건 방식',
        data_type: 'select',
        default_value: 'not_empty',
        options: [
          { value: 'exists', label: '값 존재' },
          { value: 'empty', label: '비어 있음' },
          { value: 'not_empty', label: '비어 있지 않음' },
          { value: 'equals', label: '같음' },
          { value: 'not_equals', label: '같지 않음' },
          { value: 'greater_than', label: '초과' },
          { value: 'greater_than_or_equal', label: '이상' },
          { value: 'less_than', label: '미만' },
          { value: 'less_than_or_equal', label: '이하' },
          { value: 'contains', label: '텍스트 포함' },
          { value: 'not_contains', label: '텍스트 미포함' },
          { value: 'starts_with', label: '텍스트 시작 일치' },
          { value: 'ends_with', label: '텍스트 끝 일치' },
          { value: 'regex', label: '정규식 일치' },
          { value: 'type_is', label: '타입 일치' },
        ],
      },
      {
        key: 'expected_type',
        label: '기대 타입',
        data_type: 'select',
        default_value: 'string',
        options: [
          { value: 'string', label: '문자열' },
          { value: 'number', label: '숫자' },
          { value: 'boolean', label: '불리언' },
          { value: 'array', label: '배열' },
          { value: 'object', label: '객체' },
          { value: 'null', label: 'null' },
        ],
      },
    ],
    color: '#7e57c2',
  },
  {
    name: 'API 요청',
    description: 'URL, 방식, 헤더, 키/값 입력, 본문을 조합해 외부 API를 호출하고 응답값 하나를 내보내.',
    category: 'utility',
    exposedInputs: [
      {
        key: 'url',
        label: 'URL',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
        description: '호출할 http 또는 https API 주소야.',
      },
      {
        key: 'method',
        label: '방식',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
        default_value: 'POST',
        description: 'GET, POST, PUT, PATCH, DELETE 중 하나야.',
      },
      {
        key: 'headers',
        label: '헤더',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        default_value: [],
        description: '요청 헤더를 key/value 목록으로 설정해.',
      },
      {
        key: 'values',
        label: '입력 값',
        direction: 'input',
        data_type: 'json',
        required: false,
        multiple: false,
        default_value: [],
        description: '요청에 보낼 key/value 목록이야. GET은 query, 그 외 방식은 body로 보내.',
      },
      {
        key: 'payload',
        label: '본문 값',
        direction: 'input',
        data_type: 'any',
        required: false,
        multiple: false,
        description: '업스트림 JSON, 텍스트, 이미지, 비디오 data URL 같은 값을 본문에 추가해.',
      },
      {
        key: 'body_mode',
        label: '본문 형식',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'auto',
        description: 'auto, json, form 중 하나야. auto는 파일 data URL이 있으면 form-data를 사용해.',
      },
      {
        key: 'timeout_ms',
        label: '타임아웃(ms)',
        direction: 'input',
        data_type: 'number',
        required: false,
        multiple: false,
        default_value: 30000,
      },
    ],
    outputPorts: [
      {
        key: 'response',
        label: '응답',
        direction: 'output',
        data_type: 'any',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.api_request' },
    uiSchema: [
      {
        key: 'method',
        label: '방식',
        data_type: 'select',
        default_value: 'POST',
        options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
      },
      {
        key: 'headers',
        label: '헤더',
        data_type: 'json',
        default_value: [],
        ui_hint: 'key_value_entries',
      },
      {
        key: 'values',
        label: '입력 값',
        data_type: 'json',
        default_value: [],
        ui_hint: 'key_value_entries',
      },
      {
        key: 'body_mode',
        label: '본문 형식',
        data_type: 'select',
        default_value: 'auto',
        options: ['auto', 'json', 'form'],
      },
      {
        key: 'timeout_ms',
        label: '타임아웃(ms)',
        data_type: 'number',
        default_value: 30000,
        min: 1000,
        max: 300000,
      },
    ],
    color: '#26a69a',
  },
  {
    name: 'Base64 인코딩',
    description: '텍스트, JSON, data URL 값을 Base64 텍스트로 변환해.',
    category: 'utility',
    exposedInputs: [
      {
        key: 'value',
        label: '값',
        direction: 'input',
        data_type: 'any',
        required: true,
        multiple: false,
      },
      {
        key: 'input_mode',
        label: '입력 형식',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'auto',
        description: 'auto, text, json, data_url 중 하나야.',
      },
    ],
    outputPorts: [
      {
        key: 'base64',
        label: 'Base64',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.base64_encode' },
    uiSchema: [
      {
        key: 'input_mode',
        label: '입력 형식',
        data_type: 'select',
        default_value: 'auto',
        options: ['auto', 'text', 'json', 'data_url'],
      },
    ],
    color: '#26a69a',
  },
  {
    name: 'Base64 디코딩',
    description: 'Base64 텍스트를 텍스트, JSON, data URL 값으로 변환해.',
    category: 'utility',
    exposedInputs: [
      {
        key: 'base64',
        label: 'Base64',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
      },
      {
        key: 'output_mode',
        label: '출력 형식',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'data_url',
        description: 'text, json, data_url 중 하나야.',
      },
      {
        key: 'mime_type',
        label: 'MIME 타입',
        direction: 'input',
        data_type: 'text',
        required: false,
        multiple: false,
        default_value: 'application/octet-stream',
      },
    ],
    outputPorts: [
      {
        key: 'value',
        label: '값',
        direction: 'output',
        data_type: 'any',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.base64_decode' },
    uiSchema: [
      {
        key: 'output_mode',
        label: '출력 형식',
        data_type: 'select',
        default_value: 'data_url',
        options: ['data_url', 'text', 'json'],
      },
      {
        key: 'mime_type',
        label: 'MIME 타입',
        data_type: 'text',
        default_value: 'application/octet-stream',
        placeholder: 'image/png, video/mp4, application/json',
      },
    ],
    color: '#26a69a',
  },
  {
    name: 'JSON 추출',
    description: 'JSON 입력에서 tags, user.name, items[0].title 같은 경로의 값만 골라내.',
    category: 'utility',
    exposedInputs: [
      {
        key: 'json',
        label: 'JSON',
        direction: 'input',
        data_type: 'json',
        required: true,
        multiple: false,
        description: '값을 추출할 원본 JSON이야.',
      },
      {
        key: 'path',
        label: '추출 경로',
        direction: 'input',
        data_type: 'text',
        required: true,
        multiple: false,
        default_value: 'tags',
        description: '꺼낼 값의 경로야. 예: tags 또는 items[0].title',
      },
    ],
    outputPorts: [
      {
        key: 'text',
        label: '텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
      {
        key: 'json',
        label: 'JSON',
        direction: 'output',
        data_type: 'json',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.json_extract' },
    uiSchema: [
      {
        key: 'path',
        label: '추출 경로',
        data_type: 'text',
        default_value: 'tags',
        placeholder: '예: tags 또는 items[0].title',
        ui_hint: 'inline',
      },
    ],
    color: '#78909c',
  },
  {
    name: '텍스트 변환',
    description: '텍스트, 프롬프트, JSON 같은 입력을 문자열로 정규화한 뒤 정규식 추출/치환과 접두어·접미어 조합으로 후처리해.',
    category: 'utility',
    exposedInputs: [
      {
        key: 'value',
        label: '값',
        direction: 'input',
        data_type: 'any',
        required: true,
        multiple: false,
        description: '텍스트, 프롬프트, JSON, 숫자 같은 업스트림 값을 문자열로 바꿔서 처리해.',
      },
    ],
    outputPorts: [
      {
        key: 'text',
        label: '변환 텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.regex_text_transform' },
    uiSchema: [
      {
        key: 'mode',
        label: '변환 방식',
        data_type: 'select',
        default_value: 'extract',
        options: ['extract', 'replace'],
      },
      {
        key: 'pattern',
        label: '정규식',
        data_type: 'text',
        placeholder: '예: ^\s*([^,\n]+)',
      },
      {
        key: 'flags',
        label: '플래그',
        data_type: 'text',
        placeholder: '예: i 또는 gm',
      },
      {
        key: 'replacement',
        label: '치환 문자열',
        data_type: 'text',
        placeholder: '예: @$1,',
      },
      {
        key: 'group_index',
        label: '추출 그룹 번호',
        data_type: 'number',
      },
      {
        key: 'prefix',
        label: '접두어',
        data_type: 'text',
        placeholder: '예: @',
      },
      {
        key: 'suffix',
        label: '접미어',
        data_type: 'text',
        placeholder: '예: ,',
      },
    ],
    color: '#8d6e63',
  },
  {
    name: '이미지에서 작가 추출',
    description: '설정된 Kaloscope 작가 태거를 실행해서 작가나 스타일 힌트를 추출해.',
    category: 'analysis',
    exposedInputs: [
      {
        key: 'image',
        label: '이미지',
        direction: 'input',
        data_type: 'image',
        required: true,
        multiple: false,
        description: '작가나 스타일을 추출할 입력 이미지야.',
      },
    ],
    outputPorts: [
      {
        key: 'artist_text',
        label: '작가 텍스트',
        direction: 'output',
        data_type: 'text',
        required: true,
        multiple: false,
      },
      {
        key: 'artist_json',
        label: '작가 JSON',
        direction: 'output',
        data_type: 'json',
        required: false,
        multiple: false,
      },
    ],
    internalFixedValues: { operation_key: 'system.extract_artist_from_image' },
    uiSchema: [],
    color: '#ef5350',
  },
];
