export { default as LegacyHomePage } from '../pages/Home/HomePage'
export { default as LegacySettingsPage } from '../pages/Settings/SettingsPage'
export { default as LegacyWorkflowFormPage } from '../pages/Workflows/WorkflowFormPage'
export { default as LegacyWorkflowGeneratePage } from '../pages/Workflows/WorkflowGeneratePage'
export { default as LegacyNAITab } from '../pages/ImageGeneration/NAI/NAITab'
export { default as LegacyComfyUITab } from '../pages/ImageGeneration/ComfyUITab'
export { default as LegacyWildcardTab } from '../pages/ImageGeneration/WildcardTab'
